name: CI

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  pipeline:
    uses: jvcm-infra/workflows/.github/workflows/cli-ts.yml@main
    with:
      app: taverna
      pre_install: "ln -sf $HOME/tools/neo-matrix $(dirname $GITHUB_WORKSPACE)/neo-matrix"
